config/routes.rb
Rails.application.routes.draw do

  resources :prestamos do
    resources :devoluciones
  end
  resources :clientes
  resources :equipos
  resources :tipos
  resources :marcas
  resources :usuarios
  get 'signup' => 'usuarios#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'prestamos#index'

end

app/models/marca.rb
class Marca < ActiveRecord::Base
  has_many :equipos
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:nombre)
    end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.erb
<div class="row">
  <div class="container">
    <div class="large-12 columns">
      <div class="center">
        <%= form_for(@marca) do |f| %>
          <% if @marca.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

              <ul>
              <% @marca.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :nombre %><br>
            <%= f.text_field :nombre %>
          </div>
          <div class="row no-padding">
            <div class="large-3 columns no-padding clearfix">
              <div class="actions">
                <%= f.submit "Ingresar Marca", class: 'button' %>
              </div>
            </div>
            <div class="large-3 columns no-padding">
              <div class="actions">
                <%= link_to 'Cancelar', marcas_path, class: 'alert button float-right' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/marcas/edit.html.erb
<h1>Editing Marca</h1>

<%= render 'form' %>

<%= link_to 'Show', @marca %> |
<%= link_to 'Back', marcas_path %>

app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row header-section">
  <div class="large-8 columns no-padding">
    <h1>Marcas</h1>
  </div>
  <div class="large-2 columns no-padding">
    <%= link_to 'Agregar Marca', new_marca_path, class: 'button button-add' %>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.nombre %></td>
        <td><%= link_to 'Show', marca %></td>
        <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
        <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marca', new_marca_path %>

app/views/marcas/new.html.erb
<div class="row header-section">
  <div class="large-8 columns no-padding">
    <h1>Agregar Marca</h1>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Back', marcas_path %>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @marca.nombre %>
</p>

<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>