config/routes.rb
Rails.application.routes.draw do

  resources :prestamos do
    resources :devoluciones
  end
  resources :clientes
  resources :equipos
  resources :tipos
  resources :marcas
  resources :usuarios
  get 'signup' => 'usuarios#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'prestamos#index'

end

app/models/prestamo.rb
class Prestamo < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :equipo
  belongs_to :usuario
  has_many :entregas
  has_many :devoluciones

  # Verifica si el ID del equipo se encuentra prestado.
  validates_uniqueness_of :equipo_id, message: "se encuentra prestado.", conditions: -> {where(estado: 'Prestado')}
  validates_presence_of :equipo_id, message: "Por favor seleccione un equipo"
  validates_presence_of :cliente_id, message: "Por favor seleccione a cliente"
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_prestamo, only: [:show, :edit, :update, :destroy]

  # GET /prestamos
  # GET /prestamos.json
  def index
    @prestamos = Prestamo.all
  end

  # GET /prestamos/1
  # GET /prestamos/1.json
  def show
  end

  # GET /prestamos/new
  def new
    @prestamo = Prestamo.new
  end

  # GET /prestamos/1/edit
  def edit
  end

  # POST /prestamos
  # POST /prestamos.json
  def create
    @prestamo = Prestamo.new(prestamo_params)
    @prestamo.usuario_id = current_user.id if current_user
    @prestamo.estado = "Prestado"
    respond_to do |format|
      if @prestamo.save
        format.html { redirect_to @prestamo, notice: 'Prestamo was successfully created.' }
        format.json { render :show, status: :created, location: @prestamo }
      else
        format.html { render :new }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prestamos/1
  # PATCH/PUT /prestamos/1.json
  def update
    respond_to do |format|
      if @prestamo.update(prestamo_params)
        format.html { redirect_to @prestamo, notice: 'Prestamo was successfully updated.' }
        format.json { render :show, status: :ok, location: @prestamo }
      else
        format.html { render :edit }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamos/1
  # DELETE /prestamos/1.json
  def destroy
    @prestamo.destroy
    respond_to do |format|
      format.html { redirect_to prestamos_url, notice: 'Prestamo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestamo
      @prestamo = Prestamo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prestamo_params
      params.require(:prestamo).permit(:descripcion, :fechaPrestamo, :estado, :equipo_id, :usuario_id, :cliente_id)
    end
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/views/prestamos/_form.html.erb
<div class="row">
  <div class="container">
    <div class="large-12 columns">
      <div class="center">
        <%= form_for(@prestamo) do |f| %>
          <% if @prestamo.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@prestamo.errors.count, "error") %> prohibited this prestamo from being saved:</h2>

              <ul>
              <% @prestamo.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :equipo %><br>
            <%= collection_select(:prestamo, :equipo_id, Equipo.all, :id, :codUss, prompt: true) %>
          </div>
          <div class="field">
            <%= f.label :cliente %><br>
            <%= collection_select(:prestamo, :cliente_id, Cliente.all, :id, :nombre_con_apellido, prompt: true) %>
          </div>
          <div class="field">
            <%= f.label :descripcion %><br>
            <%= f.text_area :descripcion %>
          </div>

          <div class="row no-padding">
            <div class="large-3 columns no-padding clearfix">
              <div class="actions">
                <%= f.submit "Ingresar Préstamo", class: 'button' %>
              </div>
            </div>
            <div class="large-3 columns no-padding">
              <div class="actions">
                <%= link_to 'Cancelar', prestamos_path, class: 'alert button float-right' %>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/prestamos/_form_devolucion.html.erb

  <div class="row header-section">
    <div class="large-12 columns no-padding">
      <h1>Entregar</h1>
    </div>
  </div>

  <div class="row">
    <div class="container">
      <div class="large-6 columns">
        <%= form_for([@prestamo, @prestamo.devoluciones.build]) do |f| %>
          <div>
            <%= f.text_field :usuario_id, value: current_user.id, class: 'hide' %>
          </div>
          <p>
            <%= f.label :descripcion %>
            <%= f.text_area :descripcion %>
          </p>
          <p>
            <%= f.submit "Devolver", class: 'success button'  %>
          </p>
        <% end %>
      </div>
    </div>
  </div>

app/views/prestamos/_form_devoluciones.html.erb
<h2>Entrega</h2>
<%= form_for([@prestamo, @prestamo.entregas.build]) do |f| %>
  <p>
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </p>

  <p>
    <%= f.label :fechaEntrega %>
    <%= f.datetime_select :fechaEntrega %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/prestamos/_show_devoluciones.html.erb
<p>
  <strong>Descripcion:</strong>
  <%= @prestamo.devolucione.descripcion %>
</p>

<p>
  <strong>Fechadevolucion:</strong>
  <%= @devolucione.fechaDevolucion %>
</p>

<p>
  <strong>Prestamo:</strong>
  <%= @devolucione.prestamo %>
</p>

app/views/prestamos/edit.html.erb
<h1>Editing Prestamo</h1>

<%= render 'form' %>

<%= link_to 'Show', @prestamo %> |
<%= link_to 'Back', prestamos_path %>

app/views/prestamos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row header-section">
  <div class="large-8 columns no-padding">
    <h1>Préstamos</h1>
  </div>
  <div class="large-2 columns no-padding">
    <%= link_to 'Agregar Préstamo', new_prestamo_path, class: 'button button-add' %>
  </div>
</div>

<table class="stack table-prestamo">
  <thead>
    <tr>
      <th>Código USS</th>
      <th>Equipo</th>
      <th>Cliente</th>
      <th>Fecha Préstamo</th>
      <th>Estado</th>
      <th>Prestado Por:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prestamos.each do |prestamo| %>
      <% if prestamo.estado == "Prestado" %>
        <tr class="td-red">
          <td><%= prestamo.equipo.codUss %></td>
          <td><%= prestamo.equipo.marca.nombre << " " << prestamo.equipo.modelo %></td>
          <td><%= prestamo.cliente.nombre << " " << prestamo.cliente.apellido %></td>
          <td><%= prestamo.created_at.strftime("%d %b %y / %H:%M Hrs") %></td>
          <td><%= prestamo.estado %></td>
          <td><%= prestamo.usuario.nombre << " " << prestamo.usuario.apellido %></td>
          <td><%= link_to 'Show', prestamo %></td>
          <td><%= link_to 'Edit', edit_prestamo_path(prestamo) %></td>
          <td><%= link_to 'Destroy', prestamo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% else %>
        <tr class="td-green">
          <td><%= prestamo.equipo.codUss %></td>
          <td><%= prestamo.equipo.marca.nombre << " " << prestamo.equipo.modelo %></td>
          <td><%= prestamo.cliente.nombre << " " << prestamo.cliente.apellido %></td>
          <td><%= prestamo.created_at.strftime("%d %b %y / %H:%M Hrs") %></td>
          <td><%= prestamo.estado %></td>
          <td><%= prestamo.usuario.nombre << " " << prestamo.usuario.apellido %></td>
          <td><%= link_to 'Show', prestamo %></td>
          <td><%= link_to 'Edit', edit_prestamo_path(prestamo) %></td>
          <td><%= link_to 'Destroy', prestamo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/prestamos/new.html.erb
<div class="row header-section">
  <div class="large-8 columns no-padding">
    <h1>Nuevo Préstamo</h1>
  </div>
</div>

<%= render 'form' %>

app/views/prestamos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="large-12 columns">

  <div class="row">
    <div class="large-12 columns no-padding">
      <div class="actions">
        <%= link_to 'Atrás', prestamos_path, class: 'button button-add' %>
      </div>
    </div>
  </div>

  <div class="show-container">
    <div class="show-card bg-orange">
      <p class="head-devoluciones">
        <strong>Fecha Préstamo:</strong>
        <%= @prestamo.created_at.strftime("%d %b %y / %H:%M Hrs") %>
      </p>

      <p class="head-devoluciones">
        <strong>Estado:</strong>
        <%= @prestamo.estado %>
      </p>

      <p class="head-devoluciones">
        <strong>Descripción:</strong><br>
        <%= @prestamo.descripcion %>
      </p>
    </div>
  </div>
</div>

<% if @prestamo.estado == "Prestado" %>
  <%= render 'form_devolucion' %>
<% else %>
  <!-- Ingresar div bloqueado. -->
  <%= render @prestamo.devoluciones %>
<% end %>