config/routes.rb
Rails.application.routes.draw do

  resources :prestamos do
    resources :devoluciones
  end
  resources :clientes
  resources :equipos
  resources :tipos
  resources :marcas
  resources :usuarios
  get 'signup' => 'usuarios#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'prestamos#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :prestamos

  def nombre_con_apellido
    "#{nombre} #{apellido}"
  end
end

app/models/devolucione.rb
class Devolucione < ActiveRecord::Base
  belongs_to :prestamo
  belongs_to :usuario
end

app/models/entrega.rb
class Entrega < ActiveRecord::Base
  belongs_to :prestamo
  belongs_to :usuario
end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  belongs_to :tipo
  belongs_to :marca
  has_many :prestamos
end

app/models/marca.rb
class Marca < ActiveRecord::Base
  has_many :equipos
end

app/models/prestamo.rb
class Prestamo < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :equipo
  belongs_to :usuario
  has_many :entregas
  has_many :devoluciones

  # Verifica si el ID del equipo se encuentra prestado.
  validates_uniqueness_of :equipo_id, message: "se encuentra prestado.", conditions: -> {where(estado: 'Prestado')}
  validates_presence_of :equipo_id, message: "Por favor seleccione un equipo"
  validates_presence_of :cliente_id, message: "Por favor seleccione a cliente"
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  has_many :equipos
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_secure_password
  has_many :prestamos
  has_many :devoluciones
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_marca, only: [:show, :edit, :update, :destroy]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marca_params
      params.require(:marca).permit(:nombre)
    end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :require_user, only: [:index, :show]
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/devoluciones_helper.rb
module DevolucionesHelper
end

app/helpers/entregas_helper.rb
module EntregasHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class="expanded row">
      <div class="large-4 columns">
        <h2>LogoUSS</h2>
      </div>
      <div class="large-8 columns">
        <h2>Prestamos Informática Valdivia USS</h2>
      </div>
    </div>
</header>

app/views/layouts/_menu_aplicacion.html.erb
<!-- Menu Arriba -->
<div class="expanded row">
  <div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><%= link_to 'Préstamos', prestamos_path %></li>
        <li><%= link_to 'Equipos', equipos_path %></li>
        <li><%= link_to 'Marcas de Equipos', marcas_path %></li>
        <li><%= link_to 'Tipos de Equipos', tipos_path %></li>
        <li><%= link_to 'Clientes', clientes_path %></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <% if current_user %>
        <ul class="dropdown menu" data-dropdown-menu>
          <li>
            <%= current_user.nombre << " " << current_user.apellido %>
          </li>
          <li><%= link_to "Cerrar Sesión", logout_path, method: "delete" %></li>
        </ul>
      <% else %>
        <ul>
          <li></li>
        </ul>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Sistema de Prestamos de Equipos Informática USS Valdivia" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <%= render 'layouts/menu_aplicacion' %>

    <!-- Contenido tablas etc -->
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
  </div>


  </body>
</html>